In [3]:
import numpy as np
np.random.seed(42)

# Problem 1: Tạo hai ma trận 3x3 với các phần tử integer ngẫu nhiên từ 1 - 10.

In [7]:
# Your code here
a = np.random.randint(1,11, size = (3,3))
b = np.random.randint(1,11,size = (3,3))
a,b


(array([[ 6,  2,  5],
        [ 1, 10,  6],
        [ 9,  1, 10]]),
 array([[3, 7, 4],
        [9, 3, 5],
        [3, 7, 5]]))

# Problem 2: Thực hiện phép cộng phần tử, nhân từng phần tử, tích vô hướng với hai ma trận vừa được tạo.


In [10]:
# Your code here
c = a+b
d = a*b
e = np.dot(a,b)
c,d,e


(array([[ 9,  9,  9],
        [10, 13, 11],
        [12,  8, 15]]),
 array([[18, 14, 20],
        [ 9, 30, 30],
        [27,  7, 50]]),
 array([[ 51,  83,  59],
        [111,  79,  84],
        [ 66, 136,  91]]))

# Problem 3: VIết hàm nhận vào một mảng Numpy, sau đó trả về tổng tất cả các phần tử của chúng


In [14]:
# Your code here
def total(a):
  return np.sum(a)

a = np.array([[ 9,  9,  9],
              [10, 13, 11],
              [12,  8, 15]])

print(total(a))


96
